Integrate Jenkins CICD  (#19)
# Ready for CR 🕺🏼

### Remarks
1. Couldn't solve the annoying error: 
```
Failed to read test report file ...../test-reports/TEST-fusedrug_examples.tests.test_interaction_cat_dti.InterCatDtiTestCase-20230323060652.xml
org.dom4j.DocumentException: Error on line 114 of document  : An invalid XML character (Unicode: 0x1b) was found in the CDATA section.
```
Somehow Lightning's logger prints a special unicode character (0x1b)
that Jenkins can't parse. I added a workaround for that but it is
something that we should figure out (either in this PR or in a future
one).

2. The original submodule repository is not stable so I switched to
@alex-golts 's fork which should be stable.
3. `fusedrug/utils/file_formats/tests/test_indexed_fasta_custom.py`
crashed due some changes in #20. I added a workaround but generally
speaking I don't like that the output changes its structure (once a
string and once a tuple). What do you think @YoelShoshan ?

---------

Co-authored-by: Sagi Polaczek <sagi.polaczek@ibm.com>